version: "3.7"

services:
  podping-cloud:
    image: podcastindexorg/podcasting20-podping.cloud:latest
    init: true
    restart: unless-stopped
    stop_grace_period: 1m
    user: "1000:1000"
    ports:
      - 80:80
    volumes:
      - /data:/data
    environment:
      ZMQ_SOCKET_ADDR: "192.168.69.69:9999"
    networks:
      podping:
        ipv4_address: 192.168.69.68
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"

  hive-writer:
    image: docker.io/podcastindexorg/podping-hivewriter:latest
    command: ["server"]
    init: true
    restart: unless-stopped
    stop_grace_period: 1m
    user: "1000:1000"
    env_file:
      - /opt/podping.cloud/hivewriter.env
    networks:
      podping:
        ipv4_address: 192.168.69.69
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"

networks:
  podping:
    ipam:
      driver: default
      config:
        - subnet: "192.168.69.0/24"