// @generated by the capnpc-rust plugin to the Cap'n Proto schema compiler.
// DO NOT EDIT.
// source: org/podcastindex/podping/hivewriter/podping_medium.capnp


#[repr(u16)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PodpingMedium {
  Podcast = 0,
  PodcastL = 1,
  Music = 2,
  MusicL = 3,
  Video = 4,
  VideoL = 5,
  Film = 6,
  FilmL = 7,
  Audiobook = 8,
  AudiobookL = 9,
  Newsletter = 10,
  NewsletterL = 11,
  Blog = 12,
  BlogL = 13,
}
impl ::capnp::traits::FromU16 for PodpingMedium {
  #[inline]
  fn from_u16(value: u16) -> ::core::result::Result<PodpingMedium, ::capnp::NotInSchema> {
    match value {
      0 => ::core::result::Result::Ok(PodpingMedium::Podcast),
      1 => ::core::result::Result::Ok(PodpingMedium::PodcastL),
      2 => ::core::result::Result::Ok(PodpingMedium::Music),
      3 => ::core::result::Result::Ok(PodpingMedium::MusicL),
      4 => ::core::result::Result::Ok(PodpingMedium::Video),
      5 => ::core::result::Result::Ok(PodpingMedium::VideoL),
      6 => ::core::result::Result::Ok(PodpingMedium::Film),
      7 => ::core::result::Result::Ok(PodpingMedium::FilmL),
      8 => ::core::result::Result::Ok(PodpingMedium::Audiobook),
      9 => ::core::result::Result::Ok(PodpingMedium::AudiobookL),
      10 => ::core::result::Result::Ok(PodpingMedium::Newsletter),
      11 => ::core::result::Result::Ok(PodpingMedium::NewsletterL),
      12 => ::core::result::Result::Ok(PodpingMedium::Blog),
      13 => ::core::result::Result::Ok(PodpingMedium::BlogL),
      n => ::core::result::Result::Err(::capnp::NotInSchema(n)),
    }
  }
}
impl ::capnp::traits::ToU16 for PodpingMedium {
  #[inline]
  fn to_u16(self) -> u16 { self as u16 }
}
impl ::capnp::traits::HasTypeId for PodpingMedium {
  #[inline]
  fn type_id() -> u64 { 0xaae8_1675_a576_a280u64 }
}
