[tool.poetry]
name = "hive-watcher"
version = "0.2.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyzmq = "^22.1.0"
lighthive = {git = "https://git@github.com/agates/lighthive.git", rev = "a2af5b83481924334ed6e681529118c13b361a8b"}
pendulum = "^2.1.2"
beem = "^0.24.26"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
isort = "^5.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py37', 'py38', 'py39', 'py310']

[tool.isort]
profile = "black"
multi_line_output = 3
